### ISSUE TITLE
Command palette button needs some love

### ISSUE THREAD

**Issue by rouilj** [benwinding/command-pal#12]
The little command terminal button on the lower left is a nice touch for mobile users. However it is too small.
Also it has a weird spacing compared to the border which is noticeable with larger line-heights.

Changing the svg declaration to add a viewport:
```
<svg viewport="0 0 24 24"... >
```
will let you scale up the size of the svg terminal prompt using css. The css I would use with it is:
```
.mobile-button > svg {
   width: 44px;
   height: 44px;
   display: block;
}
```
to provide a minimal size of 44px for the button.

`display: block` is used to remove space below the svg icon. Since the default display is inline, the icon
sits on the text baseline.

I would also add a title tag as the first element between the > for the svg tag and first g tag.
```
<title>Click here to open command palette.</title>
```
so the svg has some a11y accessible name. In thinking about it, probably adding that text as aria-label to the button element would be better. Maybe aria-label="Open Command Palette" would work.

Getting full aria working for command-pal is another set of steps, but I expect it would be useful for users.

**Comment by benwinding** [comment]
Hi @rouilj,

Fixed the issues mentioned above, with a few referenced commits 👍 

I also want to thank you for the detail and time you're putting into these issues, the quality and thought put into them is appreciated 🙏

Seems like you're getting a detailed understanding of the library, so feel free to submit PR's here for fixes you think are appropriate, local development on this is pretty simple ([see instructions here](https://benwinding.github.io/command-pal/docs/#local-development))

Cheers
Ben
