### ISSUE TITLE
Dynamic list of commands?

### ISSUE THREAD

**Issue by roamhacker** [benwinding/command-pal#4]
Hello, very nice tool you have built here. is it possible to provide a list of dynamic commands? Basically I have a need where I have a list of commands that are static and a list that I have to generate dynamically when the palette is opened.

The examples you have here seem to be static, predefined in advanced.

Thank you

**Comment by benwinding** [comment]
Hi @roamhacker,

Thanks for checking out the project! 

Yes, this is a common use-case, and I've updated the docs to describe it. Basically the command array can be changed at runtime, and the command-pallete will update the list automatically.

- [Demo Dynamic](https://benwinding.github.io/command-pal/demos/cp-dynamic)
 
Quick snippet on how to achieve this.
``` js
const commands = [
  {
    name: "Add Command to List",
    handler: () => {
      commands.push({
        name: 'New Command',
        handler: () => {
          // Do something
        },
      });
    },
  },
];
const c = new CommandPal({
  hotkey: "ctrl+space",
  commands: commands,
});
c.start();
```

Cheers,
Ben

**Comment by roamhacker** [comment]
Thank you for response. Do you plan to continue to support this project? Any new features planned? Will likely add it to my Roam42 tool and would contribute back.

**Comment by benwinding** [comment]
Yes I plan to support this for the future, feel free to:
- Submit bugs & feature requests
- Submit PR's
I'm not currently using the project, but would love for it to be used somewhere!
