### ISSUE TITLE
key activation in textarea

### ISSUE THREAD

**Issue by roamhacker** [benwinding/command-pal#5]
Ben,
Is it possible for the activation key to work from a textara? I have CP loading when nothing is loaded in the UI, but it would be nice if it can be activated from any context.

Warm regards

**Comment by benwinding** [comment]
Apologies for the late response, yes this is possible now in `0.2.8`.

There's a new flag called `hotkeysGlobal` if you set this to true, then the shortcut keys will work on any input field.

Cheers,
Ben
