### ISSUE TITLE
Detecting key state when executed

### ISSUE THREAD

**Issue by roamhacker** [benwinding/command-pal#6]
Ben,
is it possible to detect the shift and ctrl key states when an items is selected with keyboard (Shift+enter or shift+click).

thank you

**Comment by benwinding** [comment]
Hi @roamhacker, 
From what I can gather, you want to have primary actions and secondary actions per command, is that correct? 
If so, then I don't think it should be implemented. The command palette's strength comes from it's ease of use and simplicity. 
By mapping multiple actions to a single command makes it confusing in my opinion and is a reason why it's not seen in other command palette implementations. The search functionality is what gives it power, try listing more commands nested under predictable menu structures.
Ben
